---
- hosts: all
  become: true
  vars:
    default_container_name: Covid19-Consumer
    default_container_image: registry.gitlab.com/riteshahuja13/usc-covidapp
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Login into gitlab registry
      docker_login:
        registry_url: registry.gitlab.com
        username: riteshahuja13
        password: 
    - name: Pull Docker Image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
        force_source: yes
        state: present

    - name: Create container
      docker_container:
        name: "{{ default_container_name }}"
        hostname: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        network_mode: host
        networks_cli_compatible: yes
        volumes:
          - /var/log/nginx:/var/log/nginx
        log_driver: json-file
        log_opt: max-size=1g , max-file=10
        state: started
    - name: prune old images
      docker_prune:
        images: yes
