version: '3.3'

networks:
  covid-19-network:
    driver: bridge

# docker push registry.gitlab.com/riteshahuja13/usc-covidapp
services:

    open-resty-base:
      image: open-resty-base
      build:
        context: ./open-resty-base

    covid-19-web1:
      image: registry.gitlab.com/riteshahuja13/usc-covidapp
      build:
        context: ./openresty/
        args:
          redis_dsn: ${redis_dsn}
          mysql_dsn: ${mysql_dsn}
          mysql_user: ${mysql_user}
          mysql_password: ${mysql_password}
          jwt_secret: ${jwt_secret}
          android_secret_captcha: ${android_secret_captcha}
          ios_secret_captcha: ${ios_secret_captcha}
          _env: ${_env}
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      container_name: covid-19-web1
      volumes:
        - ./openresty/logs:/var/log/nginx
        - ./openresty/root/usr/local/openresty/lualib/lua_scripts:/usr/local/openresty/lualib/lua_scripts
      ports:
        - 80:80
      networks:
        - covid-19-network
      links:
        - redis
        - mysql

    mysql:
      image: covid_mysql
      build:
        context: ./MySql/
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: example
      networks:
        - covid-19-network

    redis:
      image: redis
      ports:
        - 6379:6379
      networks:
        - covid-19-network